const events = [
  {
    id: 1,
    name: "Android Study Jams - 1",
    date: "2021-11-29",
    day: "Mon",
    about:"❓ Want to build apps? ❓Don't know where to start? GDSC AISSMS IOIT brings to you ANDROID STUDY JAMS to kickstart your journey as an Android Developer. 💡 TRACKS - Android basics in kotlin course 📌What's in it for you? ✨Learn Android fundamentals from basics. ✨Earn badges for Google Developer Profile. ✨Get certificate of completion. ✨Get ready for Associate Android Developer Exam. ✨ Develop real-world Android Apps in team.",
    speaker: "Prathamesh Chaudhari",
    imageSrc: "",
    imageSrcSet: "",
    dataAos: "fade-up",
  },
  {
    id: 2,
    name: "Road to Google Cloud Certifications",
    date: "2021-10-28",
    day: "Thu",
    about:"📌93% of IT decision-makers around the world agree that certified employees provide added value above and beyond the cost of certification. 📌87% of Google Cloud-certified individuals are more confident about their cloud skills. 📌More than 1 in 4 Google Cloud certified individuals took on more responsibilities or leadership roles in their respective domains. Google Cloud certifications validate your expertise and showcase your ability to transform businesses with Google Cloud technology. Join us for the event CloudFest 2.0: Road to Google Cloud Certifications with GDSC AISSMS IOIT that will take you to Google Cloud certification journey and will be helping you to begin your journey of becoming Google Cloud certified. Discover all about Google Cloud Certifications and get all your queries answered!",
    speaker: "Magda Jary",
    imageSrc: "",
    imageSrcSet: "",
    dataAos: "fade-right",
  },
  {
    id: 3,
    name: "Orientation of 30 Days of Google Cloud",
    date: "2021-09-22",
    day: "Wed",
    about:"30 days of Google Cloud is an amazing program for the cloud engineering aspirants also for those who wish to explore the cloud domain in detail with working models. This program would provide an opportunity for participants to build, develop, test and deploy their models on Google Cloud Platform free of cost. Not only this, to honor your accomplishments, Google will provide you with exciting goodies and schwags! In this info-session we'll have a look through every step of the program and will make you familiar to the program.",
    speaker: "Shriniwas Khond",
    imageSrc: "",
    imageSrcSet: "",
    dataAos: "fade-left",
  },
  {
    id: 4,
    name: "GDSC Kick-off!",
    date: "2021-09-15",
    day: "Wed",
    about:"What is GDSC?. Meet the Core Team & Faculty Advisor. Events Launch. Introducing Developer Hacks - 21.",
    speaker: "Core Team",
    sponsor: "Tech Mahindra",
    recording: "https://youtu.be/DKzCNpLOjX4",
    imageSrc: "",
    imageSrcSet: "",
    dataAos: "fade-up",
  },
  {
    id: 5,
    name: "Intro-Meet of GDSC, AISSMS IOIT",
    date: "2021-08-26",
    day: "Thu",
    about:"Introducing GDSC at AISSMS IOIT, GDSC membership, Core team applications.",
    speaker: "Prarthana Chandak",
    guest: "Ankita Ugale",
    recording: "https://youtu.be/qWuQMssG0nQ",
    imageSrc: "",
    imageSrcSet: "",
    dataAos: "fade-right",
  },
];

export default events;
