const Android = [
  {
    id: 1,
    name: "Parth Desai",
    position: "Android Lead",
    image: "",
    alt: "Lead_Image",
    col: 3,
    linkedin: "",
    instagram: "",
    github: "",
  },
  {
    id: 2,
    name: "Prathamesh Chaudhari",
    position: "Android Co-Lead",
    image: "",
    alt: "Co_Lead_Image",
    col: 3,
    linkedin: "",
    instagram: "",
    github: "",
  },
  {
    id: 3,
    name: "Aniruddh Karekar",
    position: "Android Member",
    image: "https://lh3.google.com/u/0/d/1O5lbgQ6CDQ88GSgWQ93hasHykAUMArxC=w3000-h5334-iv1",
    alt: "Member_Image",
    col: 3,
    linkedin: "",
    instagram: "",
    github: "",
  },
  {
    id: 4,
    name: "Het Bhalala",
    position: "Android Member",
    image: "",
    alt: "Member_Image",
    col: 3,
    linkedin: "",
    instagram: "",
    github: "",
  },
];

export default Android;
