const Android = [
  {
    id: 1,
    name: "Parth Desai",
    position: "Android Lead",
    image: "",
    alt: "Lead_Image",
    col: 3,
    linkedin: "https://www.linkedin.com/in/parth-desai-021027",
    instagram: "https://www.instagram.com/redpaladin1001",
    github: "https://www.linkedin.com/in/parth-desai-021027",
  },
  {
    id: 2,
    name: "Prathamesh Chaudhari",
    position: "Android Co-Lead",
    image: "",
    alt: "Co_Lead_Image",
    col: 3,
    linkedin: "https://www.linkedin.com/in/prathmeshchaudhari",
    instagram: "https://www.instagram.com/@prathmeshc_",
    github: "https://github.com/Retr094",
  },
  {
    id: 3,
    name: "Aniruddh Karekar",
    position: "Android Member",
    image: "https://i.ibb.co/WfJYrbK/IMG-3341.jpg",
    alt: "Member_Image",
    col: 3,
    linkedin: "",
    instagram: "",
    github: "",
  },
  {
    id: 4,
    name: "Het Bhalala",
    position: "Android Member",
    image: "",
    alt: "Member_Image",
    col: 3,
    linkedin: "https://www.linkedin.com/in/het-bhalala-38a979204",
    instagram: "https://www.instagram.com/hetbhalala11",
    github: "",
  },
];

export default Android;
