const Management = [
  {
    id: 1,
    name: "Omkar Danave",
    position: "Management Lead",
    image: "https://i.ibb.co/wpc9D2Y/Omkar-Danave.png",
    alt: "Lead_Image",
    col: 4,
    linkedin: "https://www.linkedin.com/in/omdanave/",
    instagram: "https://www.instagram.com/__life.racer/",
    github: "https://github.com/omkardanave",
    link: "",
  },
  {
    id: 2,
    name: "Krishna Waske",
    position: "Management Member",
    image: "https://i.ibb.co/wRgG5wr/Krishna-Waske.jpg",
    alt: "Member_Image",
    col: 4,
    linkedin: "https://www.linkedin.com/in/krishna-waske-329a99178",
    instagram: "https://www.instagram.com/waskekrishna/",
    github: "https://github.com/GHkrishna",
    link: "",
  },
  {
    id: 3,
    name: "Shrusti Kharche",
    position: "Management Member",
    image: "https://i.ibb.co/YTyNmPX/Shrushti-Kharche.jpg",
    alt: "Member_Image",
    col: 4,
    linkedin: "",
    instagram: "",
    github: "",
    link: "",
  },
  {
    id: 4,
    name: "Sanyukta Kamble",
    position: "Social Media Lead",
    image: "https://i.ibb.co/f49wvHR/Sanyukta-kamble.jpg",
    alt: "Lead_Image",
    col: 6,
    linkedin: "https://www.linkedin.com/in/sanyukta-kamble-a158711a6",
    instagram: "https://www.instagram.com/of.sanyukta",
    github: "https://github.com/sanyukta111",
    link: "",
  },
  {
    id: 5,
    name: "Pornima Lokhande",
    position: "Design Lead",
    image: "https://i.ibb.co/PNrtZN4/Pornima-Lokhande.jpg",
    alt: "Lead_Image",
    col: 6,
    linkedin: "www.linkedin.com/in/pornima-lokhande-31b480200",
    instagram: "https://www.instagram.com/ponu234",
    github: "https://github.com/PornimaLokhande",
    link: "",
  },
];

export default Management;
