const Web = [
  {
    id: 1,
    name: "Ashish Patil",
    position: "Web Development Lead",
    image: "https://i.ibb.co/Q6yRs2J/Ashish-Patil-GDSC-Web.jpg",
    alt: "Lead_Image",
    col: 3,
    linkedin: "https://www.linkedin.com/in/ashish-patil-👨‍💻-ab2879192",
    instagram: "https://www.instagram.com/ashishpatil2831/",
    github: "https://github.com/Ashish2831",
  },
  {
    id: 2,
    name: "Ganesh Birajdar",
    position: "Web Development Co-Lead",
    image: "https://i.ibb.co/t83qp1V/Ganesh-Birajdar.jpg",
    alt: "Co_Lead_Image",
    col: 3,
    linkedin: "www.linkedin.com/in/ganesh-birajdar-a3a959219",
    instagram: "https://www.instagram.com/ganeshb_009",
    github: "https://github.com/ganeshbirajdar09",
  },
  {
    id: 3,
    name: "Sarang Kulkarni",
    position: "Web Development Member",
    image: "https://i.ibb.co/9HZ1nvp/Sarang-Kulkarni.jpg",
    alt: "Member_Image",
    col: 3,
    linkedin: "https://www.linkedin.com/in/sarangkulkarni99",
    instagram: "https://www.instagram.com/_sarang_kulkarni_",
    github: "https://github.com/sarangkulkarni99",
  },
  {
    id: 4,
    name: "Prakalp Pande",
    position: "Web Development Member",
    image: "https://i.ibb.co/dL6FjFc/PRAKALP-PANDE.jpg",
    alt: "Member_Image",
    col: 3,
    linkedin: "https://www.linkedin.com/in/prakalp-pande-a56219220/",
    instagram: "https://www.instagram.com/prakalp_pande_/",
    github: "https://github.com/PRAKALP-PANDE",
  },
];

export default Web;
